# Generated by Django 5.1.5 on 2025-11-17 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expertise', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Very poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('liked_most', models.TextField(blank=True, help_text='What did you like the most?')),
                ('to_improve', models.TextField(blank=True, help_text='What can be improved?')),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='digital', help_text='Where this feedback came from (paper/digital/etc.)', max_length=50)),
                ('demo_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.democlass')),
            ],
        ),
        migrations.AddField(
            model_name='democlass',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_classes', to='feedback.trainer'),
        ),
    ]
