# Generated by Django 5.1.5 on 2025-11-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='liked_most',
            field=models.TextField(help_text='What did you like the most?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='to_improve',
            field=models.TextField(help_text='What can be improved?'),
        ),
    ]
